# Pull official Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy the app file
COPY app.py .

# Run the Python app
CMD ["python", "app.py"]

# docker build -t hello-world-python-app .
# docker images
# docker ps -a
# docker run --rm hello-world-python-app
