services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    networks:
      - app-network
    depends_on:
      - server
    environment:
      - PYTHONUNBUFFERED=1

networks:
  app-network:
    driver: bridge